modules/admin/controllers/PostController.php
<?php

namespace app\modules\admin\controllers;

use ozerich\filestorage\models\File;

use app\models\OrderMedia;
use Yii;
use app\models\PostSearch;
use app\models\Post;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\UploadedFile;
use ozerich\filestorage\storage\FileStorage;


/**
 * PostController implements the CRUD actions for Post model.
 */
class PostController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['login', 'signup', 'logout', 'index'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['login', 'signup'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['error'],
                        'roles' => ['uploadInformation'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['logout', 'index'],
                        'roles' => ['changePost'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                    'delete-media' => ['POST']
                ],
            ],
        ];
    }
    public function actionAll($group)
    {
        $searchModel = new  PostSearch(); //::find()->where(['group' => $group])->orderBy(['created_at' => SORT_DESC]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $group);
        return $this->render(
            // $group . '/all',
            $group.'/all',
            [
                'searchModel' => $searchModel,
                'pagination' => ['pageSize' => 20],
                'dataProvider' => $dataProvider,

            ]
        );
    }
    /**
     * Lists all Post models.
     * @return mixed
     */
    public function actionIndex($group = null, $category = null, $sub = null)
    {
        // Kategoriyasiz postlarni guruh bo'ylab sarlaydi
        if ($group && !$sub) {
            $query = Post::find()->where(['group' => $group])->orderBy(['created_at' => SORT_DESC]);
            $dataProvider = new ActiveDataProvider([
                'query' => $query,
                'pagination' => ['pageSize' => 20],
            ]);
            return $this->render($group . '/index', [
                'dataProvider' => $dataProvider,
            ]);
        } else 
        if ($category) {
            // Agar kop kategoriyali bolsa shu kategoriyalar listini chiqaradi
            $query = Post::find()->where(['group' => $category . '_category'])->orderBy(['created_at' => SORT_DESC]);
            $dataProvider = new ActiveDataProvider([
                'query' => $query,
                'pagination' => ['pageSize' => 20],
            ]);
            return $this->render($category . '_category/index', [
                'dataProvider' => $dataProvider,
            ]);
        } else
        if ($sub && $group) {
            // Agar kop kategoriyali bolsa bitta kategoriyaga tegishli postlarni oladi
            $query = Post::find()->where(['group' => strstr($group, '_', true), 'category_id' => $sub])->orderBy(['created_at' => SORT_DESC]);
            $dataProvider = new ActiveDataProvider([
                'query' => $query,
                'pagination' => ['pageSize' => 20],
            ]);
            return $this->render(strstr($group, '_', true) . '/index', [
                'dataProvider' => $dataProvider,
            ]);
        }
        // $searchModel = new PostSearch();
        // $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        // return $this->render('index', [
        //     'searchModel' => $searchModel,
        //     'dataProvider' => $dataProvider,
        // ]);
    }

    /**
     * Displays a single Post model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $model->updateCounters(['views' => 1]);
        if ($model) {
            return $this->render($model->group . '/view', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Creates a new Post model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($group = null, $sub = null)
    {
        if ($group) {
            $model = new Post();
            $model->group = $group;
            if ($sub) {
                $model->category_id = $sub;
                $model->group = strstr($group, '_', true);
            }
            $model->title = '{"ru":null, "en":null, "uz-Lat":null, "uz-Cyr":null}';
            $model->content = '{"ru":null, "en":null, "uz-Lat":null, "uz-Cyr":null}';
            $model->short_content = '{"ru":null, "en":null, "uz-Lat":null, "uz-Cyr":null}';
            $model->content_html = '{"ru":null, "en":null, "uz-Lat":null, "uz-Cyr":null}';
            $model->meta_title = '{"ru":null, "en":null, "uz-Lat":null, "uz-Cyr":null}';
            $model->meta_description = '{"ru":null, "en":null, "uz-Lat":null, "uz-Cyr":null}';
            $model->meta_keywords = '{"ru":null, "en":null, "uz-Lat":null, "uz-Cyr":null}';
            $model->status = 'inactive';
            $newId = $model->save();
            return $this->redirect(['update', 'id' => $model->id]);
        } else {
            return 'Error';
        }
    }

    /**
     * Updates an existing Post model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    /* app\controllers\UploadController.php */

    public function actionImage($group, $id)
    {
        if (Yii::$app->request->isPost) {
            Yii::$app->response->format = 'json';
            $files = UploadedFile::getInstancesByName('file');
            if (count($files) > 0) {
                foreach ($files as $item) {
                    $media = Yii::$app->media->createFileFromUploadedFile($item, 'document');
                    $mediaOrder = new OrderMedia();
                    $mediaOrder->media_id = (int) $media->id;
                    $mediaOrder->model_id = (int) $id;
                    $mediaOrder->category = $group;
                    $mediaOrder->url = $media->getPath();
                    $mediaOrder->save();
                }
                return [
                    'success' => true
                ];
            } else {
                return [
                    'success' => false
                ];
            }
        }
    }
    public function actionDeleteMedia()
    {
        $request = Yii::$app->request;
        $mediaOrder = OrderMedia::findOne(['media_id' => $request->post('key')]);
        $media = File::findOne(['id' => $request->post('key')]);
        Yii::$app->media->deleteFile($media);
        $media->delete();
        $mediaOrder->delete();
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return ['success' => 'true'];
    }
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $mediaOrder = OrderMedia::find()->where(['model_id' => $id, 'category'=>$model->group])->all();
        $files = [];
        foreach ($mediaOrder as $item) {
            $media = File::findOne(['id' => $item->media_id]);
            array_push($files, $media);
        }
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if ($model->category_id > 0) {
                return $this->redirect(['index', 'group' => $model->group . '_category', 'sub' => $model->category_id]);
            }
            return $this->redirect([
                'index', 'group' => $model->group,

                'model' => $model,
                'files' => $files
            ]);
        }
        return $this->render($model->group . '/update', [
            'model' => $model,
            'files' => $files
        ]);
    }

    /**
     * Deletes an existing Post model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $post = $this->findModel($id);
        $group = $post['group'];
        $mediaOrder = OrderMedia::find()->where(['model_id' => $id])->all();
        foreach ($mediaOrder as $item) {
            $media = File::findOne(['id' => $item->media_id]);
            Yii::$app->media->deleteFile($media);
            $media->delete();
        }
        OrderMedia::deleteAll(['model_id' => $id]);
        $post->delete();
        return $this->redirect(['index', 'group' => $group]);
    }

    /**
     * Finds the Post model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Post the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Post::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/admin/views/post/photos/_form.php
<?php

use yii\helpers\Html;
use yii\web\View;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Post */
/* @var $form yii\widgets\ActiveForm */

@app\assets\AdminAsset::register($this);


?>
<div class="post-form">
    <?php $form = ActiveForm::begin();
    $hasLagnguage = array_map(function ($item) use ($form, $model) {
        return [
            'label' => strtoupper($item),
            // 'content' => "<div>". $form->field($model, "configtitle[{$item}]", ['labelOptions' => ['label' => "Заголовок( {$item} )"]])->textInput(['maxlength' => true,'value'=>yii\helpers\Json::decode($model->title)[$item]]).$form->field($model, "configcontent[{$item}]", ['labelOptions' => ['label' => "Контент( {$item} )"]])->textInput(['maxlength' => true,'value'=>yii\helpers\Json::decode($model->content)[$item]])."</div>"
            'content' => "<div>" .
                $form->field($model, "configtitle[{$item}]", ['labelOptions' => ['label' => "Заголовок"]])->textInput(['maxlength' => true, 'value' => yii\helpers\Json::decode($model->title)[$item]]) .
                $form->field($model, "configcontent[{$item}]", ['labelOptions' => ['label' => "Настройка значения"]])->textarea(['style'=>'height:200px;','maxlength' => true, 'value' => yii\helpers\Json::decode($model->content)[$item]]) .
                "</div>"
        ];
    }, ['ru', 'uz-Cyr', "uz-Lat", 'en']);

    ?>

    <?php
    $this->registerJs(
        "$('#showLinkInput').on('change', function(e) {
            var vals=e.target.selectedOptions[0].value
            if (vals==1||vals==2){
                $('#link_type').css({display: 'block'})
            }else{
                $('#link_type').css({display: 'none'})
            }
         });",
        View::POS_READY
    );
    echo yii\bootstrap\Tabs::widget([
        'items' => $hasLagnguage
    ]);
    ?>
    <?= $form->field($model, 'alias')->textInput() ?>
    <?= $form->field($model, 'group')->textInput(['maxlength' => true, 'readonly' => true, 'value' => $model->group]) ?>
    <!-- <?= $form->field($model, 'content_html')->textarea(['rows' => 6]) ?> -->

    <!-- <?= $form->field($model, 'short_content')->textarea(['rows' => 6]) ?> -->

    <?= $form->field($model, 'status')->dropDownList(['active' => 'Активный', 'inactive' => 'Неактивный'], ['class'=>'col-sm-6 form-control','value' => ($model->status == 'inactive') ? 'active' : ""]) ?>
    <?=Html::label('Тип загрузок')?>
    <?=Html:: dropDownList( 'type', '',['1' => 'Youtube', '2' => 'Mover'], ['prompt'=>'Загрузит из другого сайта', 'class'=>'form-control col-sm-6','id'=>'showLinkInput']) ?>
    <?= $form->field($model, 'link', ['labelOptions'=>['label'=>'Ссылка на сайт']])->textInput(['class'=>'form-control d-none ', 'id'=>'link_type']) ?>     
    <!-- <?= $form->field($model, 'option')->dropDownList(['yes' => 'Yes', 'no' => 'No',], ['prompt' => '']) ?> -->
    <!-- <?= $form->field($model, 'options')->textInput() ?> -->


    <!-- <?= $form->field($model, 'tags')->textarea(['rows' => 6]) ?> -->

    <!-- <?= $form->field($model, 'meta_title')->textarea(['rows' => 6]) ?> -->

    <!-- <?= $form->field($model, 'meta_description')->textarea(['rows' => 6]) ?> -->

    <!-- <?= $form->field($model, 'meta_keywords')->textarea(['rows' => 6]) ?> -->
    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

modules/admin/views/post/photos/edit.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Post */

// $this->title =  'Admin';

?>
<div class="post-update">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

modules/admin/views/post/photos/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\models\PostSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title ='Фото лента';
$this->params['breadcrumbs'][] = $this->title;
$request = Yii::$app->request;
?>
<div class="post-index">

    <h1><?= Html::encode($this->title) ?></h1> 
    <p>
        <?= Html::a('Добавить', ['create', 'group'=>$_GET['group']], ['class' => 'btn btn-success']) ?>
    </p>



    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'attribute' => 'title',
                'label' => 'Заголовок',
                'value' => function ($item) {
                    return (json_decode($item->title))->ru;
                }
            ],
            [
                'attribute' => 'short_content',
                'label' => 'Короткое содержание',
                'value' => function ($model) {
                    return (json_decode($model->short_content)->ru);
                }
            ],
            [
                'attribute' => 'status',
                'label' => 'Статус',
                'contentOptions' => function ($model) {
                    return  ['class' => ($model->status == 'active') ? 'bg-green' : 'bg-yellow'];
                },
                'value'=>function($model){
                    return ($model->status == 'active') ? 'Активный' : 'Неактивный';
                }
            ],
            // 'category_id',
            // 'category_id2',
            // 'group',
            // 'alias:ntext',
            //'title:ntext',
            //'content:ntext',
            //'content_html:ntext',
            //'short_content:ntext',
            //'status',
            //'option',
            //'options',
            //'views',
            //'tags:ntext',
            //'meta_title:ntext',
            //'meta_description:ntext',
            //'meta_keywords:ntext',
            //'sort_order',
            //'created_at',
            //'updated_at',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

modules/admin/views/post/photos/update.php
<?php

use app\components\helpers\MyHelpers;
use yii\helpers\Html;
use kartik\file\FileInput;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Post */

// $this->title = 'Update Post: ' . $model->title;
// $this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
// $this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
// $this->params['breadcrumbs'][] = 'Update';
?>
<div class="post-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
    <?php echo FileInput::widget([
        'name' => 'file',
        'options' => [
            'multiple' => true,
            'id' => 'hyperFiles'
        ],
        'pluginOptions' => [
            'uploadUrl' => Url::to(['post/image', 'id' => $model->id, 'group' => $model->group]),
            'maxFileCount' => 10,
            'uploadAsync' => true,
            'showUpload' => false,
            'overwriteInitial' => false,
            'minFileCount' => 1,
            'maxFileCount' => 10,
            'initialPreviewAsData' => true,
            'browseOnZoneClick' => true,
            'initialPreview' => MyHelpers::getMediaUrls($files),
            'initialPreviewConfig' =>
            MyHelpers::getEachMediaInfo($files),
            'maxFileSize' => 10000,
        ],
        'pluginEvents' => [
            'filebatchselected' => '
            function(event, files) {
                $("#hyperFiles").fileinput("upload");
            }
            '
        ]
    ]); ?>
</div>

modules/admin/views/post/photos/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Post */

// $this->title = $model->title;
// $this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
// $this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="post-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'category_id',
            'category_id2',
            'group',
            'alias:ntext',
            'title:ntext',
            'content:ntext',
            'content_html:ntext',
            'short_content:ntext',
            'status',
            'option',
            'options',
            'views',
            'tags:ntext',
            'meta_title:ntext',
            'meta_description:ntext',
            'meta_keywords:ntext',
            'sort_order',
            'created_at',
            'updated_at',
        ],
    ]) ?>

</div>